/* Campeones Wild Rift: tipo de daño + traits para los 141 campeones.
 * GENERADO por tools/build_champions.py — ver DATA_SOURCES.md (aproximado).
 * dmg: AP | AD | mixto. traits: tanque, curación, control, asesino, escudo.
 * clase/roles: WR Wiki (Module:ChampionDataWR). img: retrato WR Wiki (arte © Riot Games). */
(typeof window !== 'undefined' ? window : globalThis).WR_CHAMPS = {
  "Aatrox": {"dmg": "AD", "traits": ["tanque", "curación"], "clase": ["Luchador"], "roles": ["baron", "jungle"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/aatrox.webp"},
  "Ahri": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Asesino"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/ahri.webp"},
  "Akali": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino"], "roles": ["mid", "baron"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/akali.webp"},
  "Akshan": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino", "Tirador"], "roles": ["mid"], "build": {"baron": "AD", "mid": "AD"}, "estilo": ["crit"], "img": "assets/champions/akshan.webp"},
  "Alistar": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/alistar.webp"},
  "Ambessa": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["jungle", "baron"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/ambessa.webp"},
  "Amumu": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque"], "roles": ["jungle", "support", "baron"], "build": {"jungle": "tanque", "support": "tanque"}, "estilo": [], "img": "assets/champions/amumu.webp"},
  "Annie": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Soporte"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/annie.webp"},
  "Ashe": {"dmg": "AD", "traits": ["control"], "clase": ["Tirador", "Soporte"], "roles": ["adc", "support"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/ashe.webp"},
  "Aurelion Sol": {"dmg": "AP", "traits": [], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/aurelion-sol.webp"},
  "Aurora": {"dmg": "AP", "traits": ["asesino"], "clase": ["Mago", "Asesino"], "roles": ["mid", "baron"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/aurora.webp"},
  "Bard": {"dmg": "AP", "traits": ["curación", "control"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": [], "img": "assets/champions/bard.webp"},
  "Blitzcrank": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/blitzcrank.webp"},
  "Brand": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/brand.webp"},
  "Braum": {"dmg": "AP", "traits": ["tanque", "control", "escudo"], "clase": ["Soporte", "Tanque"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/braum.webp"},
  "Caitlyn": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/caitlyn.webp"},
  "Camille": {"dmg": "AD", "traits": [], "clase": ["Luchador"], "roles": ["baron", "jungle"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/camille.webp"},
  "Cho'Gath": {"dmg": "AP", "traits": ["tanque", "curación", "control"], "clase": ["Tanque", "Mago"], "roles": ["baron"], "build": {}, "estilo": [], "img": "assets/champions/chogath.webp"},
  "Corki": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc", "mid"], "build": {"mid": "AD", "adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/corki.webp"},
  "Darius": {"dmg": "AD", "traits": ["curación"], "clase": ["Luchador"], "roles": ["baron", "jungle"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/darius.webp"},
  "Diana": {"dmg": "AP", "traits": ["asesino"], "clase": ["Luchador", "Mago"], "roles": ["mid", "baron", "jungle"], "build": {"jungle": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/diana.webp"},
  "Dr. Mundo": {"dmg": "AD", "traits": ["tanque", "curación"], "clase": ["Luchador", "Tanque"], "roles": ["baron", "jungle"], "build": {"baron": "tanque", "jungle": "tanque"}, "estilo": [], "img": "assets/champions/dr-mundo.webp"},
  "Draven": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/draven.webp"},
  "Ekko": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino", "Luchador"], "roles": ["mid", "jungle", "baron"], "build": {"jungle": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/ekko.webp"},
  "Evelynn": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino"], "roles": ["jungle"], "build": {"jungle": "AP"}, "estilo": [], "img": "assets/champions/evelynn.webp"},
  "Ezreal": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": [], "img": "assets/champions/ezreal.webp"},
  "Fiddlesticks": {"dmg": "AP", "traits": ["curación", "control"], "clase": ["Mago"], "roles": ["jungle"], "build": {"jungle": "AP"}, "estilo": [], "img": "assets/champions/fiddlesticks.webp"},
  "Fiora": {"dmg": "AD", "traits": ["curación"], "clase": ["Luchador", "Asesino"], "roles": ["baron"], "build": {"baron": "AD"}, "estilo": [], "img": "assets/champions/fiora.webp"},
  "Fizz": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino", "Mago"], "roles": ["mid", "baron", "jungle"], "build": {"jungle": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/fizz.webp"},
  "Galio": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Mago"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "tanque"}, "estilo": [], "img": "assets/champions/galio.webp"},
  "Garen": {"dmg": "AD", "traits": ["tanque"], "clase": ["Luchador", "Tanque"], "roles": ["baron"], "build": {"baron": "AD"}, "estilo": [], "img": "assets/champions/garen.webp"},
  "Gnar": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Luchador", "Tanque"], "roles": ["baron"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/gnar.webp"},
  "Gragas": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Luchador", "Mago"], "roles": ["jungle", "baron", "mid"], "build": {"baron": "tanque", "jungle": "AP", "mid": "AP", "support": "tanque"}, "estilo": [], "img": "assets/champions/gragas.webp"},
  "Graves": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["jungle", "baron"], "build": {"jungle": "AD"}, "estilo": ["crit"], "img": "assets/champions/graves.webp"},
  "Gwen": {"dmg": "AP", "traits": ["curación"], "clase": ["Luchador", "Asesino"], "roles": ["baron", "jungle"], "build": {"baron": "AP", "jungle": "AP"}, "estilo": [], "img": "assets/champions/gwen.webp"},
  "Hecarim": {"dmg": "AD", "traits": ["control"], "clase": ["Luchador", "Tanque"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/hecarim.webp"},
  "Heimerdinger": {"dmg": "AP", "traits": [], "clase": ["Mago", "Soporte"], "roles": ["mid"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/heimerdinger.webp"},
  "Irelia": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["mid", "baron"], "build": {"baron": "AD", "mid": "AD"}, "estilo": [], "img": "assets/champions/irelia.webp"},
  "Janna": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/janna.webp"},
  "Jarvan IV": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Tanque", "Luchador"], "roles": ["jungle", "baron"], "build": {"baron": "tanque", "jungle": "tanque"}, "estilo": [], "img": "assets/champions/jarvan-iv.webp"},
  "Jax": {"dmg": "AD", "traits": [], "clase": ["Luchador"], "roles": ["jungle", "baron"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/jax.webp"},
  "Jayce": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Tirador"], "roles": ["baron", "mid"], "build": {"baron": "AD", "mid": "AD"}, "estilo": [], "img": "assets/champions/jayce.webp"},
  "Jhin": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/jhin.webp"},
  "Jinx": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/jinx.webp"},
  "K'Sante": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Tanque", "Luchador"], "roles": ["baron"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/ksante.webp"},
  "Kai'Sa": {"dmg": "mixto", "traits": [], "clase": ["Tirador", "Asesino"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/kaisa.webp"},
  "Kalista": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"baron": "AD", "adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/kalista.webp"},
  "Karma": {"dmg": "AP", "traits": ["escudo"], "clase": ["Mago", "Soporte"], "roles": ["support", "mid"], "build": {"mid": "AP", "support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/karma.webp"},
  "Kassadin": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino", "Mago"], "roles": ["mid", "baron"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/kassadin.webp"},
  "Katarina": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino", "Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/katarina.webp"},
  "Kayle": {"dmg": "mixto", "traits": [], "clase": ["Luchador", "Soporte"], "roles": ["baron", "mid"], "build": {"baron": "AD", "mid": "AP"}, "estilo": [], "img": "assets/champions/kayle.webp"},
  "Kayn": {"dmg": "AD", "traits": ["curación", "asesino"], "clase": ["Luchador", "Asesino"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/kayn.webp"},
  "Kennen": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Tirador"], "roles": ["baron", "mid"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/kennen.webp"},
  "Kha'Zix": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/khazix.webp"},
  "Kindred": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": ["crit"], "img": "assets/champions/kindred.webp"},
  "Kog'Maw": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/kogmaw.webp"},
  "Lee Sin": {"dmg": "AD", "traits": ["control"], "clase": ["Luchador", "Asesino"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/lee-sin.webp"},
  "Leona": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/leona.webp"},
  "Lillia": {"dmg": "AP", "traits": ["control"], "clase": ["Luchador", "Mago"], "roles": ["jungle"], "build": {"jungle": "AP"}, "estilo": [], "img": "assets/champions/lillia.webp"},
  "Lissandra": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/lissandra.webp"},
  "Lucian": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc", "mid"], "build": {"mid": "AD", "adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/lucian.webp"},
  "Lulu": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/lulu.webp"},
  "Lux": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Mago", "Soporte"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/lux.webp"},
  "Malphite": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque"], "roles": ["support", "baron", "mid"], "build": {"baron": "tanque", "mid": "AP", "support": "tanque"}, "estilo": [], "img": "assets/champions/malphite.webp"},
  "Maokai": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["jungle", "baron", "support"], "build": {"baron": "tanque", "jungle": "tanque", "support": "tanque"}, "estilo": [], "img": "assets/champions/maokai.webp"},
  "Master Yi": {"dmg": "AD", "traits": ["curación", "asesino"], "clase": ["Asesino", "Luchador"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/master-yi.webp"},
  "Mel": {"dmg": "AP", "traits": [], "clase": ["Mago", "Soporte"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/mel.webp"},
  "Milio": {"dmg": "AP", "traits": ["curación", "escudo"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/milio.webp"},
  "Miss Fortune": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/miss-fortune.webp"},
  "Mordekaiser": {"dmg": "AP", "traits": ["escudo"], "clase": ["Luchador", "Mago"], "roles": ["baron", "jungle"], "build": {"baron": "AP", "jungle": "AP"}, "estilo": [], "img": "assets/champions/mordekaiser.webp"},
  "Morgana": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Mago", "Soporte"], "roles": ["support", "mid", "jungle"], "build": {"jungle": "AP", "mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/morgana.webp"},
  "Nami": {"dmg": "AP", "traits": ["curación", "control"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/nami.webp"},
  "Nasus": {"dmg": "AD", "traits": ["tanque", "curación"], "clase": ["Luchador", "Tanque"], "roles": ["baron"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/nasus.webp"},
  "Nautilus": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["support", "baron", "jungle"], "build": {"baron": "tanque", "jungle": "AP", "support": "tanque"}, "estilo": [], "img": "assets/champions/nautilus.webp"},
  "Nidalee": {"dmg": "AP", "traits": ["asesino"], "clase": ["Asesino", "Mago"], "roles": ["jungle"], "build": {"jungle": "AP"}, "estilo": [], "img": "assets/champions/nidalee.webp"},
  "Nilah": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["adc"], "build": {"jungle": "AD", "adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/nilah.webp"},
  "Nocturne": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino", "Luchador"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/nocturne.webp"},
  "Norra": {"dmg": "AP", "traits": [], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/norra.webp"},
  "Nunu & Willump": {"dmg": "AP", "traits": ["tanque", "curación", "control"], "clase": ["Tanque", "Mago"], "roles": ["jungle"], "build": {"jungle": "tanque"}, "estilo": [], "img": "assets/champions/nunu-and-willump.webp"},
  "Olaf": {"dmg": "AD", "traits": ["tanque", "curación"], "clase": ["Luchador"], "roles": ["jungle", "baron"], "build": {"baron": "tanque", "jungle": "tanque"}, "estilo": [], "img": "assets/champions/olaf.webp"},
  "Orianna": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Mago", "Soporte"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/orianna.webp"},
  "Ornn": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Tanque", "Luchador"], "roles": ["baron"], "build": {"baron": "tanque", "support": "tanque"}, "estilo": [], "img": "assets/champions/ornn.webp"},
  "Pantheon": {"dmg": "AD", "traits": ["control"], "clase": ["Tanque", "Luchador"], "roles": ["baron", "jungle", "mid"], "build": {"baron": "AD", "jungle": "AD", "mid": "AD"}, "estilo": [], "img": "assets/champions/pantheon.webp"},
  "Poppy": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Tanque"], "roles": ["baron", "jungle"], "build": {"baron": "tanque", "jungle": "tanque"}, "estilo": [], "img": "assets/champions/poppy.webp"},
  "Pyke": {"dmg": "AD", "traits": ["control", "asesino"], "clase": ["Soporte", "Asesino"], "roles": ["support"], "build": {"mid": "AD", "support": "AD"}, "estilo": [], "img": "assets/champions/pyke.webp"},
  "Rakan": {"dmg": "AP", "traits": ["control", "escudo"], "clase": ["Soporte", "Tanque"], "roles": ["support"], "build": {"support": "AP"}, "estilo": [], "img": "assets/champions/rakan.webp"},
  "Rammus": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque"], "roles": ["jungle"], "build": {"jungle": "tanque"}, "estilo": [], "img": "assets/champions/rammus.webp"},
  "Rell": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Tanque", "Soporte"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/rell.webp"},
  "Renekton": {"dmg": "AD", "traits": ["curación"], "clase": ["Luchador"], "roles": ["baron"], "build": {"baron": "AD"}, "estilo": [], "img": "assets/champions/renekton.webp"},
  "Rengar": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino", "Luchador"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": ["crit"], "img": "assets/champions/rengar.webp"},
  "Riven": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["baron", "jungle"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/riven.webp"},
  "Rumble": {"dmg": "AP", "traits": ["escudo"], "clase": ["Luchador", "Mago"], "roles": ["baron"], "build": {"baron": "AP", "jungle": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/rumble.webp"},
  "Ryze": {"dmg": "AP", "traits": [], "clase": ["Mago", "Luchador"], "roles": ["mid"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/ryze.webp"},
  "Samira": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/samira.webp"},
  "Senna": {"dmg": "AD", "traits": ["curación"], "clase": ["Tirador", "Soporte"], "roles": ["adc", "support"], "build": {"adc": "AD", "support": "AD"}, "estilo": ["crit", "encantador"], "img": "assets/champions/senna.webp"},
  "Seraphine": {"dmg": "AP", "traits": ["curación", "control", "escudo"], "clase": ["Mago", "Soporte"], "roles": ["support", "mid"], "build": {"mid": "AP", "support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/seraphine.webp"},
  "Sett": {"dmg": "AD", "traits": ["tanque", "escudo"], "clase": ["Luchador", "Tanque"], "roles": ["baron"], "build": {"baron": "tanque", "support": "tanque"}, "estilo": [], "img": "assets/champions/sett.webp"},
  "Shen": {"dmg": "AD", "traits": ["tanque", "control", "escudo"], "clase": ["Tanque"], "roles": ["baron", "jungle"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/shen.webp"},
  "Shyvana": {"dmg": "AD", "traits": ["tanque"], "clase": ["Luchador", "Tanque"], "roles": ["jungle"], "build": {"jungle": "tanque"}, "estilo": [], "img": "assets/champions/shyvana.webp"},
  "Singed": {"dmg": "AP", "traits": ["tanque"], "clase": ["Tanque", "Mago"], "roles": ["baron"], "build": {"baron": "AP"}, "estilo": [], "img": "assets/champions/singed.webp"},
  "Sion": {"dmg": "AD", "traits": ["tanque", "control", "escudo"], "clase": ["Tanque", "Luchador"], "roles": ["baron", "jungle"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/sion.webp"},
  "Sivir": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/sivir.webp"},
  "Skarner": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Tanque", "Luchador"], "roles": ["jungle", "baron"], "build": {"jungle": "tanque"}, "estilo": [], "img": "assets/champions/skarner.webp"},
  "Smolder": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/smolder.webp"},
  "Sona": {"dmg": "AP", "traits": ["curación", "control", "escudo"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/sona.webp"},
  "Soraka": {"dmg": "AP", "traits": ["curación"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/soraka.webp"},
  "Swain": {"dmg": "AP", "traits": ["tanque", "curación", "control"], "clase": ["Mago", "Luchador"], "roles": ["mid", "support"], "build": {"baron": "tanque", "mid": "AP", "support": "tanque"}, "estilo": [], "img": "assets/champions/swain.webp"},
  "Syndra": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/syndra.webp"},
  "Taliyah": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Soporte"], "roles": ["jungle", "mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/taliyah.webp"},
  "Talon": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino"], "roles": ["mid", "jungle"], "build": {"jungle": "AD", "mid": "AD"}, "estilo": [], "img": "assets/champions/talon.webp"},
  "Teemo": {"dmg": "AP", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["baron", "mid"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/teemo.webp"},
  "Thresh": {"dmg": "AP", "traits": ["tanque", "control"], "clase": ["Soporte", "Tanque"], "roles": ["support"], "build": {"support": "tanque"}, "estilo": [], "img": "assets/champions/thresh.webp"},
  "Tristana": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"mid": "AD", "adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/tristana.webp"},
  "Tryndamere": {"dmg": "AD", "traits": [], "clase": ["Luchador"], "roles": ["jungle", "baron"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": ["crit"], "img": "assets/champions/tryndamere.webp"},
  "Twisted Fate": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Tirador"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/twisted-fate.webp"},
  "Twitch": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc", "jungle"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/twitch.webp"},
  "Urgot": {"dmg": "AD", "traits": ["tanque", "control"], "clase": ["Luchador"], "roles": ["baron"], "build": {"baron": "tanque"}, "estilo": [], "img": "assets/champions/urgot.webp"},
  "Varus": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Mago"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/varus.webp"},
  "Vayne": {"dmg": "AD", "traits": [], "clase": ["Tirador", "Asesino"], "roles": ["adc"], "build": {"baron": "AD", "adc": "AD"}, "estilo": [], "img": "assets/champions/vayne.webp"},
  "Veigar": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/veigar.webp"},
  "Vel'Koz": {"dmg": "AP", "traits": [], "clase": ["Mago"], "roles": ["mid", "support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/velkoz.webp"},
  "Vex": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/vex.webp"},
  "Vi": {"dmg": "AD", "traits": ["control"], "clase": ["Luchador", "Asesino"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/vi.webp"},
  "Viego": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["jungle", "baron"], "build": {"jungle": "AD"}, "estilo": ["crit"], "img": "assets/champions/viego.webp"},
  "Viktor": {"dmg": "AP", "traits": [], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/viktor.webp"},
  "Vladimir": {"dmg": "AP", "traits": ["curación"], "clase": ["Mago"], "roles": ["mid", "baron"], "build": {"baron": "AP", "mid": "AP"}, "estilo": [], "img": "assets/champions/vladimir.webp"},
  "Volibear": {"dmg": "AD", "traits": ["tanque", "curación"], "clase": ["Luchador", "Tanque"], "roles": ["baron", "jungle"], "build": {"baron": "tanque", "jungle": "tanque"}, "estilo": [], "img": "assets/champions/volibear.webp"},
  "Warwick": {"dmg": "AD", "traits": ["curación", "control"], "clase": ["Luchador"], "roles": ["jungle", "baron"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/warwick.webp"},
  "Wukong": {"dmg": "AD", "traits": ["control"], "clase": ["Luchador", "Tanque"], "roles": ["jungle", "baron"], "build": {"baron": "AD", "jungle": "AD"}, "estilo": [], "img": "assets/champions/wukong.webp"},
  "Xayah": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/xayah.webp"},
  "Xin Zhao": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Tanque"], "roles": ["jungle"], "build": {"jungle": "AD"}, "estilo": [], "img": "assets/champions/xin-zhao.webp"},
  "Yasuo": {"dmg": "AD", "traits": [], "clase": ["Luchador", "Asesino"], "roles": ["mid", "baron"], "build": {"baron": "AD", "mid": "AD"}, "estilo": ["crit"], "img": "assets/champions/yasuo.webp"},
  "Yone": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino", "Luchador"], "roles": ["mid", "baron"], "build": {"baron": "AD", "mid": "AD"}, "estilo": ["crit"], "img": "assets/champions/yone.webp"},
  "Yunara": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/yunara.webp"},
  "Yuumi": {"dmg": "AP", "traits": ["curación", "escudo"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"support": "AP"}, "estilo": ["encantador"], "img": "assets/champions/yuumi.webp"},
  "Zed": {"dmg": "AD", "traits": ["asesino"], "clase": ["Asesino"], "roles": ["mid", "baron", "jungle"], "build": {"jungle": "AD", "mid": "AD"}, "estilo": [], "img": "assets/champions/zed.webp"},
  "Zeri": {"dmg": "AD", "traits": [], "clase": ["Tirador"], "roles": ["adc"], "build": {"adc": "AD"}, "estilo": ["crit"], "img": "assets/champions/zeri.webp"},
  "Ziggs": {"dmg": "AP", "traits": [], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/ziggs.webp"},
  "Zilean": {"dmg": "AP", "traits": ["control"], "clase": ["Soporte", "Mago"], "roles": ["support"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/zilean.webp"},
  "Zoe": {"dmg": "AP", "traits": ["control"], "clase": ["Mago"], "roles": ["mid"], "build": {"mid": "AP"}, "estilo": [], "img": "assets/champions/zoe.webp"},
  "Zyra": {"dmg": "AP", "traits": ["control"], "clase": ["Mago", "Soporte"], "roles": ["support", "mid"], "build": {"mid": "AP", "support": "AP"}, "estilo": [], "img": "assets/champions/zyra.webp"}
};
if (typeof module !== 'undefined' && module.exports) module.exports = (typeof window !== 'undefined' ? window : globalThis).WR_CHAMPS;
